accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "accounts"

urlpatterns = [
    url(r'^signup/', views.signup,name='signup'),
    url(r'^login/', views.login1,name='login'),
    ]

posts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "posts"

urlpatterns = [
    url(r'^create/', views.create,name='create'),
    url(r'(?P<pk>[0-9]+)/upvote', views.upvote,name='upvote'),
    url(r'(?P<pk>[0-9]+)/downvote', views.downvote,name='downvote'),
    ]  

redditClone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import accounts.views
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home,name='home'),
    ]   

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
import django.db
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):

    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User,on_delete=django.db.models.deletion.CASCADE)
    votes_total = models.IntegerField(default=1)
    content = models.TextField()

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

def signup(request):
    if request.method == 'POST':
        if  request.POST['password'] ==  request.POST['password1']:
            try:
                user = User.objects.get(username=request.POST['username'])
                print('user')
                return render(request,'accounts/signup.html',{'user_error':'USER ALREADY EXISTS !!!'})                       
            except:
                print('okay')
                User.objects.create_user(request.POST['username'],request.POST['email'],password =  request.POST['password'])
                return render(request,'accounts/login.html')
        else:
            print("pass")
            return render(request,'accounts/signup.html',{'Error':'Password didn\'t Match'})            
        print("THE POST WOREKD")
    return render(request,'accounts/signup.html')

def login1(request):
    if request.method == "POST":
        print('up')
        user = authenticate(username=request.POST['username'],password=request.POST['password'])
        print('down')
        if user is not None:
            print('correct')
            login(request,user)
            if 'next' in request.POST:
                if request.POST['next'] is not None:
                    return redirect(request.POST['next'])
            return render(request,'accounts/login.html',{'error':'LOGGED IN Succesfully !!!'})
        else:
            return render(request,'accounts/login.html',{'error':'Credentials are INCORRECT !!!'})
    return render(request,'accounts/login.html')    

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
# Create your views here.

@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
          post = Post() 
          post.title = request.POST['title'] 
          post.url = request.POST['url']
          post.pub_date = timezone.datetime.now()
          post.author = request.user
          post.content = request.POST['content']
          post.save()
          return redirect('home')# here we specified home because we have already mentioned it in main app's urls page
        else:
            return render(request,'posts/create.html',{'error':'Please Specify Title and URL'})

    else:
        return render(request,'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    print(len(posts))
    return render(request,'posts/home.html',{'posts':posts})

def upvote(request, pk):
    post = Post.objects.get(pk=pk)
    post.votes_total += 1
    post.save()
    return redirect(home)

def downvote(request, pk):
    post = Post.objects.get(pk=pk)
    post.votes_total -= 1
    post.save()
    return redirect(home)

accounts/templates/accounts/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>BLOG!</title>
  </head>
  <body style="background-color:rgb(196, 255, 252)">

   
<div class="container" >

<div class="border border-primary" style="border-color: orange;padding: 90px 50px; margin:150px;background-color: #afeec7">
<h1 style="text-align: center;color:#00bfff">LOGIN</h1>
<form method="POST" action='{% url "accounts:login" %}'>

    {% csrf_token %}
    {% if error %}
    <div style="margin: 10px  10px;text-align: center" class="alert alert-warning">{{error}}</div>
    {% endif %}

    {% if request.GET.next %}
    <input type = 'hidden' name = 'next' value={{ request.GET.next }}/>
    {% endif %}

    <div class="form-group">
      <label for="Username">Username</label>
      <input type="text" class="form-control" id="Username" name="username" aria-describedby="emailHelp" placeholder="Username">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name = "password"id="exampleInputPassword1" placeholder="Password">
    </div>
     
    <button type="submit" class="btn btn-primary" style="margin: 10px 42%">Submit</button>
  </form>
</div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/signup.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>BLOG!</title>
  </head>
  <body style="background-color:snow">

   
<div class="container" >

<div class="border border-primary" style="border-color: orange;padding: 90px; margin:50px;background-color: paleturquoise">
<h1 style="text-align: center;color:hsl(195, 100%, 50%)">SIGNUP</h1>
<form method="POST" action='{% url "accounts:signup" %}'>
    {% csrf_token %}  
    <div class="form-group">
      <label for="Username">Username</label>
      <input type="text" class="form-control" id="Username" name="username" aria-describedby="emailHelp" placeholder="Username">
    </div>
    {% if user_error %}
    <div style="margin: 10px  10px;text-align: center" class="alert alert-warning">{{user_error}}</div>
    {% endif %}
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name = "password"id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Confirm Password</label>
        <input type="password" name = "password1" class="form-control" id="exampleInputPassword2" placeholder="Password">
    </div>  
    {% if Error %}
    <div style="margin: 10px  10px;text-align: center" class="alert alert-warning">{{Error}}</div>
    {% endif %}
    <button type="submit" class="btn btn-primary" style="margin: 10px 42%">Submit</button>
  </form>
</div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/posts/create.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>BLOG!</title>
  </head>
<body style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/Nature/full page/img(20).jpg');">

   
<div class="container" >

<div class="border border-primary" style="border-color: orange;padding: 150px 50px; margin:50px;background-color:darkseagreen">
<h1 style="text-align: center;color:gold">*** Create Post ***</h1>
<form method="POST" action='{% url "posts:create" %}' style="padding:20px">

    {% csrf_token %}
    {% if error %}
    <div style="margin: 10px 10px;text-align: center" class="alert alert-warning">{{error}}</div>
    {% endif %}

    <div class="form-group" style="padding: 10px">
      <input type="text" style="text-align: center;height: 50px;"class="form-control" id="title" name="title" aria-describedby="emailHelp" placeholder="Title">
    </div>

    <div class="form-group" style="padding: 10px">
      <input type="text" class="form-control" style="text-align: center;height: 50px" name="url" id="url" placeholder="URL">
    </div>

    <div class="form-group" style="padding: 10px">
        <input type="text" class="form-control" style="text-align: center;height: 50px" name="content" id="content" placeholder="CONTENT">
      </div>

    <button type="submit"  class="btn btn-lg btn-block" style="margin: 25px -2px;background-color: goldenrod">CREATE</button>
  </form>
</div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/posts/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>BLOG!</title>
  </head>
<body >
    <div style="background-color: black;">
    <h1 style="text-align: center;color:gold;">*** HOME ***</h1>
    <a href="{% url 'posts:create' %}" class="float-right" style="color:blanchedalmond;margin: -3% 3%;text-decoration:  none;">New-Post</a>   
    </div>

    



    



  
<div class="container" style="display: flex; align-content: center center; margin:-7%   21%">

<div style="margin:100px 0px;align-content: center;">   


<br/> 


<div  style="">
{% for post in posts.all %}
<div   style="box-shadow: black 6px 3px 4px 5px;color:white;background-color: black;width: 70%;height: 20%;margin:25px;padding:30px; border-bottom-color: gold;border-right-color: gold;border:4px 5px" >

  <span style="color:white"><p style="text-align: left">
   
     
<p style="text-align: center; background-color: darkgoldenrod">     {{post.votes_total}} </p>
  
<p style="text-align: center;">    <a href="{{post.url}}" style="text-decoration:  none;">{{ post.title }}</a></p>
</span>
<br/>
<br/>
<p style="text-align: center">{{post.content}}</p>
<br/>
<br/>   
<p style="text-align: center">{{post.pub_date}} by {{post.author.username}}</p>
<br/>

  <div class="d-flex justify-content-between">
  <form method="POST" action='{% url "posts:upvote" post.id %}' >
      {% csrf_token %}
      
      <input type="submit" value="Like" style="color: wheat;background-color: transparent; border: 0px; margin: -100px 0px  "  >
      </form>
  <form method="POST" action='{% url "posts:downvote" post.id %}' style="margin:0px 90%">
      {% csrf_token %}
      <input type="submit" value="UnLike"  style="color: wheat;background-color: transparent; border: 0px">
  </form>
  </div>    

</div>



{% endfor %}
</div>


</div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>